# ----------- CONFIGURABLE START -----------
title:            "Temples of Code"
description:      "The knowledge vault."
url:              https://github.com/templesofcode # Site url, without a slash at the end.
signoff:          "templesofcode" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
host: 192.168.33.16

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"